# Generated by Django 3.2 on 2021-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210513_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydoctor',
            name='doc_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mydoctor',
            name='doc_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mydoctor',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
