# Generated by Django 3.2 on 2021-05-13 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210513_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydoctor',
            name='clinic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.myclinic'),
        ),
        migrations.AlterField(
            model_name='mydoctor',
            name='hospital_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.myhospital'),
        ),
        migrations.AlterField(
            model_name='myhospital',
            name='hosp_city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myhospital',
            name='hosp_fulladdress',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='myhospital',
            name='hosp_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='myhospital',
            name='hosp_state',
            field=models.CharField(max_length=30),
        ),
    ]
