# Generated by Django 3.2 on 2021-05-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210513_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhospital',
            name='hospital_id',
        ),
    ]
