# Generated by Django 3.2 on 2021-05-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_myhospital_hospital_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydoctor',
            name='doctor_id',
        ),
    ]
