# Generated by Django 3.2 on 2021-05-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_mydoctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydoctor',
            name='doc_pass',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
