# Generated by Django 3.2 on 2021-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_mydoctor_doc_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='mydiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_name', models.CharField(max_length=30)),
                ('diag_contact', models.IntegerField()),
                ('diag_pincode', models.IntegerField()),
                ('diag_city', models.CharField(max_length=15)),
                ('diag_state', models.CharField(max_length=15)),
                ('diag_fulladdress', models.CharField(max_length=500)),
                ('diag_start_time', models.TimeField()),
                ('diag_closing_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='myclinic',
            name='clinic_id',
        ),
        migrations.AddField(
            model_name='myclinic',
            name='clin_contact',
            field=models.IntegerField(default=123654789),
            preserve_default=False,
        ),
    ]
