# Generated by Django 3.2 on 2021-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210513_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclinic',
            name='clin_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mydiagnostic',
            name='diag_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myhospital',
            name='hosp_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
