# Generated by Django 3.2 on 2021-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210513_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydisease',
            old_name='dies_description',
            new_name='dise_description',
        ),
        migrations.RenameField(
            model_name='mydisease',
            old_name='dies_name',
            new_name='dise_name',
        ),
        migrations.RenameField(
            model_name='mydisease',
            old_name='dies_url',
            new_name='dise_url',
        ),
        migrations.RemoveField(
            model_name='mypatient',
            name='pat_street',
        ),
        migrations.AddField(
            model_name='mypatient',
            name='pat_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
