# Generated by Django 3.2 on 2021-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210515_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclinic',
            name='clin_city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myclinic',
            name='clin_fulladdress',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='myclinic',
            name='clin_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myclinic',
            name='clin_state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mycontactus',
            name='cs_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mycontactus',
            name='cs_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mydiagnostic',
            name='diag_city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mydiagnostic',
            name='diag_fulladdress',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='mydiagnostic',
            name='diag_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mydiagnostic',
            name='diag_state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mydisease',
            name='dise_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mydisease',
            name='dise_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='myhospital',
            name='hosp_fulladdress',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_from',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_to',
            field=models.CharField(max_length=80),
        ),
    ]
