# Generated by Django 3.2 on 2021-05-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210515_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
