# Generated by Django 3.2 on 2021-05-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210517_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreview',
            name='user_email',
            field=models.EmailField(default='abhi@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
