# Generated by Django 3.2 on 2021-05-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_mydoctor_doc_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypatient',
            name='pat_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
