# Generated by Django 3.2 on 2021-05-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_mypatient_pat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclinic',
            name='clin_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mydiagnostic',
            name='diag_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='myhospital',
            name='hosp_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
