# Generated by Django 3.2 on 2021-05-20 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210520_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='myappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_time', models.TimeField(blank=True, null=True)),
                ('app_timeofday', models.CharField(max_length=20)),
                ('app_reason', models.TextField(blank=True, null=True)),
                ('app_isactive', models.BooleanField(default=False)),
                ('app_status', models.CharField(choices=[('A', 'Approved'), ('NA', 'Not Approved'), ('P', 'Pending')], default='P', max_length=2)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mydoctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mypatient')),
            ],
        ),
    ]
