# Generated by Django 3.2 on 2021-05-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_myappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappointment',
            name='app_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
