# Generated by Django 3.2 on 2021-05-25 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_myappointment_app_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappointment',
            name='app_applytime',
            field=models.DateField(default=datetime.date(2021, 5, 25)),
        ),
    ]
