# Generated by Django 3.2 on 2021-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_myappointment_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myhelp',
            name='user_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
