# Generated by Django 3.1.2 on 2021-06-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20210606_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessages',
            name='mess_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mymessages',
            name='mess_to',
            field=models.IntegerField(),
        ),
    ]
